[package]
name = "mithril"
version = "0.1.0"
authors = [
    # Feel free to add yourself here
    "Felix Wiegand <felix-wiegand@protonmail.ch>"
]
edition = "2021"

[[test]]
name = "telemetry"
harness = false

[lib]
harness = false

[dependencies]
shared_types = { path = "../sam/shared_types" }
state_estimator = { path = "../sam/state_estimator" }
static_cell = { version = "1.1", features = ["nightly"] }
num-traits = { version = "0.2.15", default-features = false }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
postcard = "1.0"
crc = "3"
nalgebra = { version = "0.32", default-features = false, features = ["alloc", "serde-serialize-no-std", "macros"] }
siphasher = { version = "0.3", default-features = false }
rand = { version = "0.8", default-features = false }
rand_chacha = { version = "0.3", default-features = false }

# Only load dependencies for embedded when we are compiling for the flight computer,
# to avoid loading them when importing this crate from the groundstation on x86/wasm/Android
[target.'cfg(target_os = "none")'.dependencies]
embedded-hal = { version = "=1.0.0-rc.1" }
embedded-hal-async = { version = "=1.0.0-rc.1" }

cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
alloc-cortex-m = "0.4"

# TODO: move USB fix to here, create issue
# TODO: pin embassy version
embassy-stm32        = { git = "https://github.com/KoffeinFlummi/embassy", branch="usb_fix", features = ["nightly", "unstable-traits", "stm32f401rc", "unstable-pac", "memory-x", "time-driver-any", "exti"]  }
embassy-executor     = { git = "https://github.com/KoffeinFlummi/embassy", branch="usb_fix", features = ["nightly", "arch-cortex-m", "executor-thread", "executor-interrupt", "integrated-timers"] }
embassy-time         = { git = "https://github.com/KoffeinFlummi/embassy", branch="usb_fix", features = ["unstable-traits", "tick-hz-1_000_000"] }
embassy-embedded-hal = { git = "https://github.com/KoffeinFlummi/embassy", branch="usb_fix" }
embassy-sync         = { git = "https://github.com/KoffeinFlummi/embassy", branch="usb_fix", features = [] }
embassy-usb          = { git = "https://github.com/KoffeinFlummi/embassy", branch="usb_fix", features = [] }
embassy-futures      = { git = "https://github.com/KoffeinFlummi/embassy", branch="usb_fix", features = [] }

defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = [] }

[dev-dependencies]
defmt-test = "0.3"

[features]
gcs = []

# cargo build/run
[profile.dev]
codegen-units = 1
debug = "full"
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 2
overflow-checks = false

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = "full"
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 2
overflow-checks = false
